[package]
name = "aoc18"
version = "0.1.0"
authors = ["Joel Armstrong <jcarmstr@ucsc.edu>"]
edition = "2018"

[dependencies]
clap = "2.32"
failure = "0.1.3"
regex = "1"

[dev-dependencies]
rand = "0.6"